# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYK_NEWS', '0002_auto_20180721_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='news_locale',
            field=models.CharField(choices=[('TR', 'TURKEY'), ('ENG', 'ENGLAND'), ('SWE', 'SWEDEN')], max_length=3),
        ),
    ]
