# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYK_NEWS', '0008_auto_20180721_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=(112, 12), max_digits=5),
            preserve_default=False,
        ),
    ]
