# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYK_NEWS', '0009_newsitem_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
