# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LYK_NEWS', '0011_auto_20180721_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='reward',
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(default=[b'Aggregate', b'AutoField', b'Avg', b'BLANK_CHOICE_DASH', b'BigAutoField', b'BigIntegerField', b'BinaryField', b'BooleanField', b'CASCADE', b'Case', b'CharField', b'CommaSeparatedIntegerField', b'Count', b'DEFERRED', b'DO_NOTHING', b'DateField', b'DateTimeField', b'DecimalField', b'DurationField', b'EmailField', b'Empty', b'Exists', b'Expression', b'ExpressionWrapper', b'F', b'Field', b'FieldDoesNotExist', b'FileField', b'FilePathField', b'FloatField', b'ForeignKey', b'ForeignObject', b'Func', b'GenericIPAddressField', b'IPAddressField', b'ImageField', b'Index', b'IntegerField', b'Lookup', b'Manager', b'ManyToManyField', b'ManyToManyRel', b'ManyToOneRel', b'Max', b'Min', b'Model', b'NOT_PROVIDED', b'NullBooleanField', b'ObjectDoesNotExist', b'OneToOneField', b'OneToOneRel', b'OrderWrt', b'OuterRef', b'PROTECT', b'PositiveIntegerField', b'PositiveSmallIntegerField', b'Prefetch', b'ProtectedError', b'Q', b'QuerySet', b'SET', b'SET_DEFAULT', b'SET_NULL', b'SlugField', b'SmallIntegerField', b'StdDev', b'Subquery', b'Sum', b'TextField', b'TimeField', b'Transform', b'URLField', b'UUIDField', b'Value', b'Variance', b'When', b'__all__', b'__builtins__', b'__doc__', b'__file__', b'__name__', b'__package__', b'__path__', b'aggregates', b'aggregates_all', b'base', b'constants', b'deletion', b'expressions', b'fields', b'fields_all', b'functions', b'indexes', b'indexes_all', b'lookups', b'manager', b'options', b'permalink', b'prefetch_related_objects', b'query', b'query_utils', b'signals', b'sql', b'utils']),
        ),
    ]
